#!/usr/bin/env bash

REPOSITORY="/mnt/backup/repo"

pacman -Qqen > /etc/pkglist.txt
pacman -Qqem > /etc/pkglist_aur.txt

borg create -v --progress --compression zstd \
--exclude='/dev/*' \
--exclude='/proc/*' \
--exclude='/sys/*' \
--exclude='/mnt/*' \
--exclude='/run/*' \
--exclude='/tmp/*' \
--exclude='/lost+found/' \
"$REPOSITORY::{hostname}-{now:%Y%m%d-%H%M}" /;

# Capture Borg exit status
BORG_EXIT=$?

# Log backup status
if [ $BORG_EXIT -eq 0 ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S'): Backup succeeded." 
else
    echo "$(date '+%Y-%m-%d %H:%M:%S'): Backup failed with error code $BORG_EXIT."
    exit 1
fi

borg prune -v -s --list "$REPOSITORY" --keep-daily=7 --keep-weekly=4 --keep-monthly=3
borg compact -vp "$REPOSITORY"
