-- UI options
vim.o.number = true
vim.o.relativenumber = true
vim.o.cursorline = true
vim.o.pumheight = 10
vim.o.shortmess = "TIF"
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.wrap = false
vim.o.incsearch = true
vim.o.inccommand = "split"
vim.o.scrolloff = 8
vim.o.termguicolors = true
vim.o.signcolumn = "yes:1"

-- Editor options
vim.o.shiftwidth = 4
vim.o.tabstop = 4
vim.o.expandtab = true
vim.o.clipboard = "unnamedplus"
vim.o.timeout = true
vim.o.timeoutlen = 1500
vim.o.updatetime = 50
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.showmode = false
vim.o.swapfile = false
vim.o.undofile = true
vim.o.backup = false
