-- UI options
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.cursorline = true
vim.opt.pumheight = 10
vim.opt.shortmess = "TIF"
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.wrap = false
vim.opt.incsearch = true
vim.opt.inccommand = "split"
vim.opt.scrolloff = 8
vim.opt.termguicolors = true
vim.opt.signcolumn = "yes:1"

-- Edi.optr options
vim.opt.clipboard = "unnamedplus"
vim.opt.timeout = true
vim.opt.updatetime = 250
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.showmode = false
vim.opt.swapfile = false
vim.opt.undofile = true
vim.opt.backup = false
